services:
  - type: web
    name: diamond-topup-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BAY2GAME_BASE_URL
        value: https://api.bay2game.xyz/api
      - key: BAY2GAME_API_KEY
        sync: false
      - key: USD_TO_KHR_RATE
        value: "4100"
      - key: CAMRAPID_API_KEY
        sync: false
      - key: CAMRAPID_CREATE_URL
        value: https://pay.camrapidpay.com/api/v1/khqr/create-payments
      - key: CAMRAPID_CHECK_URL
        value: https://pay.camrapidpay.com/check-transaction-api
      - key: PYTHON_VERSION
        value: 3.11.9
